// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["cue", "audio"], function(Cue, Audio) {
    var AudioCue;

    return AudioCue = (function(_super) {
      __extends(AudioCue, _super);

      function AudioCue(number, name) {
        if (number == null) {
          number = "";
        }
        if (name == null) {
          name = "";
        }
        AudioCue.__super__.constructor.call(this, number, name);
        this.audio = null;
        this.start = 0;
        this.end = 0;
        this.loopStart = 0;
        this.loopEnd = 0;
      }

      return AudioCue;

    })(Cue);
  });

}).call(this);
