// Generated by CoffeeScript 1.6.2
(function() {
  define(["soundmanager"], function(SM) {
    var Audio;

    return Audio = (function() {
      function Audio(id, url, looping, volume) {
        var _this = this;

        if (looping == null) {
          looping = false;
        }
        if (volume == null) {
          volume = 1;
        }
        SM.onready(function() {
          _this.sound = SM.createSound({
            id: id,
            url: url,
            volume: volume * 100,
            autoLoad: true
          });
          return _this.sound = new Howl({
            url: urls,
            loop: looping,
            volume: volume,
            autoplay: false,
            onplay: function() {
              return console.log("Start");
            }
          });
        });
      }

      Audio.prototype.play = function() {
        return this.sound.play();
      };

      Audio.prototype.pause = function() {
        return this.sound.pause();
      };

      Audio.prototype.stop = function() {
        return this.sound.stop();
      };

      return Audio;

    })();
  });

}).call(this);
