// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var Cue;

    return Cue = (function() {
      function Cue(number, name) {
        this.number = number != null ? number : "";
        this.name = name != null ? name : "";
      }

      return Cue;

    })();
  });

}).call(this);
