// Generated by CoffeeScript 1.6.2
(function() {
  define({
    debug: true,
    log: function() {
      if (this.debug) {
        return console.log.apply(console, arguments);
      }
    }
  });

}).call(this);
