// Generated by CoffeeScript 1.6.2
(function() {
  require.config({
    paths: {
      jquery: "lib/jquery-2.0.0",
      Howler: "lib/howler",
      soundmanager: "lib/soundmanager/script/soundmanager2"
    },
    shim: {
      soundmanager: {
        exports: "soundManager",
        init: function(SM) {
          return soundManager.setup({
            url: "js/lib/soundmanager/swf",
            flashVersion: 9
          });
        }
      }
    }
  });

  require(["audio", "audiocue"], function(Audio, AudioCue) {
    return Audio.onReady(function() {
      window.A = Audio;
      window.AC = AudioCue;
      window.a = new Audio("sunday", "/sounds/sunday.mp3");
      window.ac = new AudioCue(3, "thing");
      ac.setAudio(a);
      ac.loopStart = 3000;
      ac.loopEnd = 6000;
      return ac.numLoops = 3;
    });
  });

}).call(this);
