application: cue
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /js
  static_dir: js

- url: /stylesheets
  static_dir: stylesheets

- url: /sounds
  static_dir: sounds

- url: .*
  script: cue.main.app

libraries:
- name: webapp2
  version: "2.5.2"
